### PR TITLE
Kamal 1.1.0 -> 1.3.0

### PR DESCRIPTION
**Pull request by northeastprince**
Should we look into a way to make this update automatically?

### CODE REVIEW

**Comment by guillaumebriday** [comment]
It's now 1.3 -> https://github.com/basecamp/kamal/releases/tag/v1.3.0

**Comment by guillaumebriday-pa** [comment]
It's now 1.3.1 -> https://github.com/basecamp/kamal/releases/tag/v1.3.1

**Comment by northeastprince** [comment]
It'd be nice if there was a simple way to pull it from GitHub.

**Comment by northeastprince** [comment]
5901184

**Comment by guillaumebriday-pa** [comment]
> [5901184](https://github.com/basecamp/kamal-site/commit/5901184cdb4e0f7b09e508b93e3ea65fc4de008f)

This is so frustrating to open PR for nothing..

**Pull request closed without merging**
